### ISSUE TITLE
Use yaml to disable pre-installed box software

### ISSUE THREAD

**Issue by bravo-kernel** [alt3/cakebox#48]
Would allow the user to increase performance by easily disabling non-used pre-installed box software component. E.g.

```yaml
cakebox:
  disable:
    - mongodb
    - postgres
```
