### ISSUE TITLE
NoMethodError when i try to install phpmyadmin

### ISSUE THREAD

**Issue by RicardoFideles** [alt3/cakebox#56]
/Users/ricardo/cakebox/.cakebox/Vagrantfile.rb:264:in `block in configure': undefined method `keys' for ["-apt_packages", ["phpmyadmin"]]:Array (NoMethodError)

vhosts:
  - url: cakebox.phpmyadmin
    webroot: /usr/share/phpmyadmin

databases:

extra:
  -apt_packages:
    - phpmyadmin

  -scripts:

**Comment by bravo-kernel** [comment]
This is mostly the result of your yaml file not being in the correct syntax, something you can check by using this [Ruby Yaml Linter](http://www.yamllint.com/).

At first glance I would say you need a space between the `-` and `apt_packages`.

If this doesn't please re-paste your full yaml file here but this time using [Markdown Syntax Highlighting](https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting) so it will be readable to us like this:

```yaml
extra:
  - apt_packages:
    - phpmyadmin
    - whois
    - dos2unix
```

**Comment by RicardoFideles** [comment]
This is yaml file 

```yaml
vm:
  hostname: cakebox
  ip: 10.33.10.10
  memory: 1024
  cpus: 1

cakebox:
  version: dev-dev
  debug: false
  https: false

git:
  username: 
  email:

security:
  box_public_key:
  box_private_key:

synced_folders:
  - local:  Apps
    remote: /home/vagrant/Apps

apps:

vhosts:
  - url: cakebox.phpmyadmin
    webroot: /usr/share/phpmyadmin

databases:

extra:
  - apt_packages:
    - phpmyadmin

  -scripts:

```
```ruby
This is the following error, when i try to provision

Ricardos-MacBook-Pro:cakebox ricardo$ vagrant reload --provision
/opt/vagrant/embedded/lib/ruby/2.0.0/psych.rb:205:in `parse': (<unknown>): did not find expected '-' indicator while parsing a block collection at line 29 column 3 (Psych::SyntaxError)
	from /opt/vagrant/embedded/lib/ruby/2.0.0/psych.rb:205:in `parse_stream'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/psych.rb:153:in `parse'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/psych.rb:129:in `load'
	from /Users/ricardo/cakebox/Vagrantfile:12:in `block in <top (required)>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/v2/loader.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:103:in `block (2 levels) in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:97:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:97:in `block in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:94:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/config/loader.rb:94:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:691:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:691:in `vagrantfile'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:441:in `host'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:207:in `block in action_runner'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:33:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:33:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:428:in `hook'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:673:in `unload'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:177:in `ensure in <main>'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:177:in `<main>'

```
